### ISSUE TITLE
Star a repo in trending list

### ISSUE THREAD

**Issue by jiacai2050** [jiacai2050/oh-my-github#5]

**Comment by jiahut** [comment]
`omg-repo-star: Bad request, check stderr for details.`

**Comment by jiacai2050** [comment]
Have you tried `omg-whoami` to ensure `omg` is setup correctly?

If setup correctly, you can start Emacs from terminal to check stderr logs.

**Comment by jiahut** [comment]
@jiacai2050  thinks.  It works

```elisp
 (setq omg-pat (getenv "GITHUB_TOKEN"))
```
